### ISSUE TITLE
[REQUEST] Slight change from gem to coin is needed on merchant. 

### ISSUE THREAD

**Issue by Geguuuul** [dev-jjjjjeong-bin/Invaders-SDP#106]
## Content
When I upgrade my ship, second upgrade's cost turn to gem. but It can be upgraded by coin.

I think It need to be fixed from gem to coin.

## Screenshots
Second's cost is 45gem
![image](https://github.com/user-attachments/assets/8e6107ff-5f1a-419c-bb66-7fe69eaecbd3)

But if I upgrade it, It can be done by coin.
![image](https://github.com/user-attachments/assets/f510cfbb-b058-4fa8-8207-36918b71e274)

**Comment by ise-e** [comment]
Bug fix version has been applied
