### ISSUE TITLE
[BUG] Bomb destroys ships far away

### ISSUE THREAD

**Issue by this-yujunkim** [dev-jjjjjeong-bin/Invaders-SDP#56]
### [BUG] Bomb destroys ships far away <Update-Life-Graphic>

---

### Summary
Bomb's logic is to destroy ships in their top, bottom, right, and left side. 
This bug causes bomb to destroy ships far away somehow. 

### TODO
- [ ] Fix the bomb's logic that destroy enemies.

https://github.com/user-attachments/assets/6ae34a7a-94a4-42b9-8e52-6beeb0af0779

![Bomb_Bug_log](https://github.com/user-attachments/assets/47339702-d0bc-4757-8ee5-0d692ed852d3)

**Comment by eungyu04** [comment]
The above error occurred by simply accessing the list. We are going to fix the bug by adding the distance calculation formula of the entities in the range(up, down, left, right) of the bomb.

**Comment by this-yujunkim** [comment]
> The above error occurred by simply accessing the list. We are going to fix the bug by adding the distance calculation formula of the entities in the range(up, down, left, right) of the bomb.

Thank you for your reply! I am already excited to see this bug to be fixed. Make sure to close this issue when you send PR. Keep up the good work!

**Comment by ise-e** [comment]
Bug fix version has been applied
