### ISSUE TITLE
[BUG] (Enemy Team) EnemyShipFormation.shoot causes the game to freeze unexpectedly

### ISSUE THREAD

**Issue by Guicha** [dev-jjjjjeong-bin/Invaders-SDP#79]
### BUG SUMMARY

When the player destroys all the ships that are able to shoot but leaves other ships in the formation alive, the game freezes.

### BUG DESCRIPTION 

When the player destroys all the ships that are able to shoot but leaves other ships in the formation alive, the `EnemyShipFormation.shoot` method called in the `GameScreen.update` method throws a Java exception which follows: `Index 0 out of bounds for length 0`.

![image](https://github.com/user-attachments/assets/9ab716d5-7c75-46f4-af83-87745e0c855b)

This is due to the fact that the `EnemyShipFormation.shoot` method calculate an index based on the `shooters.size()`, which in this case is 0. Therefore, the `EnemyShip shooter = this.shooters.get(index);` instruction throws an error because index 0 is out of bounds for a array of size 0.

![image](https://github.com/user-attachments/assets/4470c65b-40c0-4918-968f-ccd35b46e817)

### BUG FIX

- [ ] The easiest fix for this would be to check for the `shooters.size()` before doing any operations with the value that it returns.

**Comment by this-yujunkim** [comment]
Additionally, I had worked on similar bug. Check out 84c62b7620dae0b98b752864d67cf300e2a4f5bf and also maybe 7aa5852efe33072b1e0e6a85b4c5515fd1752917.

It is not identically the same bug, but these could help.

**Comment by Guicha** [comment]
Thank you very much for these information ! However I opened this issue because I don't think that I should modify someone else's work. Maybe you could tell the Enemy Team to address this issue ?

**Comment by this-yujunkim** [comment]
> Thank you very much for these information ! Dont worry though, the problem does not come from the fact that `shooters.size()` is 0 but from the fact that we call index 0 of this array even if it's already empty. We should try an `if` statement checking if it's empty or not. Logically speaking, we would not need to try to shoot a bullet if there's no shooter left. However I opened this issue because I don't think that I have the right to modify someone else's work. Maybe you could tell the Enemy Team to address this issue ?

Sure, I will talk about this issue today. Thank you for your bug report.

**Comment by this-yujunkim** [comment]
We failed to reproduce this bug, but anyway we added `if` statement that checks whether `shooters.isEmpty()` is false just in case it happens again.

Solved and merging at https://github.com/dev-jjjjjeong-bin/Invaders-SDP/pull/110
