### ISSUE TITLE
[BUG] (Sound Team) Sound issue causes the game to freeze. 

### ISSUE THREAD

**Issue by AaykeN** [dev-jjjjjeong-bin/Invaders-SDP#84]
## Problem Description
While playing the game, it occasionally crashes with the following error:

`Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.Map.values()" because "Sound_Operator.SoundManager.BGMs" is null
        at Sound_Operator.SoundManager.stopAllBGM(SoundManager.java:84)
        at engine.Core.main(Core.java:215)`

![image](https://github.com/user-attachments/assets/4f238d28-011b-422f-b544-c98d921646e5)

## Steps to Reproduce
1. Start the game and play through a few rounds.
2. Wait for a random amount of time; the crash does not seem tied to specific actions but happens intermittently.
3. Observe if the game crashes with the NullPointerException error.

## Additional Information
This crash tends to occur at the end of a round when background music may be stopping or transitioning.

**Comment by Kang-Minseokk** [comment]
I'll check it. Thank you for identifying the bug!
