### ISSUE TITLE
[Bug] The game freezes when the character dies after being hit by a box.

### ISSUE THREAD

**Issue by RyuJeMu** [dev-jjjjjeong-bin/Invaders-SDP#86]
## Problem Description

When the player dies after being hit by a box, the game freezes and stop screen.

`Exception in thread "main" java.lang.NullPointerException: Cannot read the array length because "image" is null
	at engine.DrawManager.drawEntity(DrawManager.java:253)
	at screen.GameScreen.draw(GameScreen.java:438)
	at screen.GameScreen.update(GameScreen.java:350)
	at screen.Screen.run(Screen.java:89)
	at screen.GameScreen.run(GameScreen.java:253)
	at engine.Frame.setScreen(Frame.java:59)
	at engine.Core.main(Core.java:172)`

<img width="760" alt="Error" src="https://github.com/user-attachments/assets/18d369fa-4fe4-462c-8ab3-f93987f49cf8">

It is confirmed that the screen freezes when the player dies after being hit by a box, regardless of whether it happens at the first or second attempt.

![image](https://github.com/user-attachments/assets/aab1780f-a6f0-4e40-a993-f1e6f28e7500)

## Todo List

1. Start the game and proceed with the gameplay.
2. When the player dies, make sure they die by being hit by a box.
3. Check if the screen freezes.

**Comment by Guicha** [comment]
We fixed this issue in the latest PR thank you for your feedback !
