### ISSUE TITLE
 [BUG] (Inventory Team) Shield item effects not applied.

### ISSUE THREAD

**Issue by LeeHyunWoo02** [dev-jjjjjeong-bin/Invaders-SDP#90]
### Title: [BUG] (Inventory Team) Shield item effects not applied.

---

### Summary

https://github.com/user-attachments/assets/aac0a4d6-9aa1-4263-bbe8-1276749ff3c8

As you can see in the video, I ate shield items and was attacked within shield validity, but I lost my stamina.

...

### BUG FIX

 Please correct the shield-related code in the item application-related logic.

**Comment by ise-e** [comment]
Currently, the bug fix has been completed and I will post a PR including other development parts.

**Comment by ise-e** [comment]
Bug fix version has been applied

**Comment by LeeHyunWoo02** [comment]
> Bug fix version has been applied

Thank you. !
