### ISSUE TITLE
[BUG] (Team International) Enemy ships keep moving down.

### ISSUE THREAD

**Issue by this-yujunkim** [dev-jjjjjeong-bin/Invaders-SDP#98]
### Title: Enemy ships keep moving down. <Update-Life-Graphic>

---

### Summary
Enemy ships keep moving down and even go through the green bottom line.
This only happens when the enemy ship's formation is circular.

Enemy formation should not go down when
`boolean isAtBottom = positionY + this.height + RADIUS > screen.getHeight() - BOTTOM_MARGIN;` is true.

![스크린샷 2024-10-16 055214](https://github.com/user-attachments/assets/55cf4589-9d68-40f9-be7d-650d609c9dff)
![스크린샷 2024-10-16 051444](https://github.com/user-attachments/assets/37bab5f7-ee9e-4975-be3f-99dbdb7f67b1)

### TODO
- [x] Check `isAtBottom`'s formula.

**Comment by Guicha** [comment]
Thank you we are working on a fix !

**Comment by this-yujunkim** [comment]
> It should be fixed by our latest PR

Seems like it is now fixed! Thanks to your team. Well done.

Closing issue, fixed at de6919a
